[build]
  command = "bun run build"
  publish = ".next"

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"

